# Generated by Django 3.1.4 on 2020-12-01 17:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('insurance_companies', '0002_auto_20201130_1621'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('employer_companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='id')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('date_of_birth', models.DateField(verbose_name='date of birth')),
                ('role', models.CharField(choices=[('unemployed', 'Unemployed'), ('employed', 'Employed'), ('ec_representative', 'Employer company representative')], max_length=30, verbose_name='role')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='id')),
                ('sdnn', models.PositiveIntegerField(verbose_name='sdnn')),
                ('sdann', models.PositiveIntegerField(verbose_name='sdann')),
                ('rmssd', models.PositiveIntegerField(verbose_name='rmssd')),
                ('start', models.DateTimeField(verbose_name='start')),
                ('end', models.DateTimeField(verbose_name='end')),
            ],
            options={
                'ordering': ['-end', 'start'],
            },
        ),
        migrations.CreateModel(
            name='InsurancePrice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='id')),
                ('price', models.PositiveIntegerField(verbose_name='insurance price')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('employer_company_coverage_price', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_insurance_price', to='employer_companies.employercompanycoverageprice')),
                ('measurement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='insurance_price', to='users.measurement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insurance_prices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='EmployedUser',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('users.user',),
        ),
        migrations.CreateModel(
            name='EmployerCompanyRepresentative',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('users.user',),
        ),
        migrations.CreateModel(
            name='UnemployedUser',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('users.user',),
        ),
        migrations.CreateModel(
            name='UnemployedUserMore',
            fields=[
                ('user', models.OneToOneField(limit_choices_to={'role': 'unemployed'}, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='unemployed_user_more', serialize=False, to='users.user')),
                ('insurance_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='insurance_companies.insurancecompany')),
            ],
        ),
        migrations.CreateModel(
            name='EmployerCompanyRepresentativeMore',
            fields=[
                ('user', models.OneToOneField(limit_choices_to={'role': 'ec_representative'}, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='employer_company_representative_more', serialize=False, to='users.user')),
                ('employer_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='representative', to='employer_companies.employercompany')),
            ],
        ),
        migrations.CreateModel(
            name='EmployedUserMore',
            fields=[
                ('user', models.OneToOneField(limit_choices_to={'role': 'employed'}, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='employed_user_more', serialize=False, to='users.user')),
                ('job', models.CharField(max_length=50, verbose_name='job')),
                ('employer_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='employer_companies.employercompany')),
            ],
        ),
    ]
