# Generated by Django 3.1.3 on 2020-11-28 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employer_companies', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employercompanyrepresentativemore',
            name='employer_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='representative', to='employer_companies.employercompany'),
        ),
    ]
