# Generated by Django 3.1.3 on 2020-11-24 15:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='measurement',
            name='user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='insurance_price',
        ),
        migrations.CreateModel(
            name='InsurancePrice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='id')),
                ('price', models.PositiveIntegerField(verbose_name='insurance price')),
                ('measurement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.measurement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
