# Generated by Django 3.1.3 on 2020-11-22 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='insurance_price',
            field=models.PositiveIntegerField(blank=True, verbose_name='insurance price'),
        ),
    ]
