# Generated by Django 3.1.3 on 2020-11-30 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employer_companies', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insuranceprice',
            name='employer_company_coverage_price',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_insurance_price', to='employer_companies.employercompanycoverageprice'),
        ),
    ]
