# Generated by Django 3.1.3 on 2020-11-21 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20201118_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='rmssd',
            field=models.PositiveIntegerField(verbose_name='rmssd'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='sdann',
            field=models.PositiveIntegerField(verbose_name='sdann'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='sdnn',
            field=models.PositiveIntegerField(verbose_name='sdnn'),
        ),
    ]
