# Generated by Django 3.1.3 on 2020-11-25 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20201125_1602'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='insuranceprice',
            options={'ordering': ['-created']},
        ),
    ]
