# Generated by Django 3.1.3 on 2020-11-30 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20201130_1235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unemployedusermore',
            name='family_member_employee',
        ),
    ]
