# Generated by Django 3.1.3 on 2020-11-18 01:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_companies', '0001_initial'),
        ('users', '0004_user_employer_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='insurance_company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clients', related_query_name='client', to='insurance_companies.insurancecompany'),
        ),
    ]
