# Generated by Django 3.1.3 on 2020-11-30 12:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InsuranceCompany',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.CharField(max_length=160, unique=True, verbose_name='name')),
                ('individual_price', models.PositiveIntegerField(verbose_name='individual price')),
                ('family_price', models.PositiveIntegerField(verbose_name='family price')),
                ('company_sale', models.FloatField(default=0.1, verbose_name='company sale')),
                ('company_employees_num', models.PositiveIntegerField(default=100, verbose_name='company employees num')),
            ],
        ),
    ]
