# Generated by Django 3.1.3 on 2020-11-22 16:11

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('insurance_companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployerCompany',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.CharField(max_length=160, unique=True, verbose_name='name')),
                ('industry', models.CharField(max_length=30, verbose_name='industry')),
                ('insurance_coverage', models.FloatField(default=0.72, max_length=1.0, verbose_name='insurance coverage')),
                ('max_family_members', models.PositiveIntegerField(default=4, verbose_name='max family members')),
                ('insurance_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_companies', related_query_name='partner_companies', to='insurance_companies.insurancecompany')),
            ],
        ),
    ]
