# Generated by Django 3.1.3 on 2020-11-17 23:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployerCompany',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.CharField(max_length=160, unique=True, verbose_name='name')),
                ('industry', models.CharField(max_length=30, verbose_name='industry')),
                ('insurance_coverage', models.FloatField(default=0.72, max_length=1.0, verbose_name='insurance coverage')),
                ('max_family_members', models.PositiveIntegerField(default=4, verbose_name='max family members')),
            ],
        ),
    ]
