# Generated by Django 3.1.4 on 2020-12-01 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employer_companies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employercompanycoverageprice',
            name='employer_company_price',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coverage_prices', to='employer_companies.employercompanyprice'),
        ),
    ]
