# Generated by Django 3.1.4 on 2020-12-02 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employer_companies', '0002_auto_20201201_2150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employercompany',
            name='max_family_members',
        ),
    ]
